// <auto-generated />
namespace Cstieg.Sales.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FreeShipping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FreeShipping));
        
        string IMigrationMetadata.Id
        {
            get { return "201801302002229_FreeShipping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
